### ISSUE TITLE
No prices visible since updating HA to 2024.4.0

### ISSUE THREAD

**Issue by sstolk90** [bajansen/home-assistant-frank_energie#107] opened 2024-04-05 06:58 UTC
I cannot get the electricity prices to work after upgrading to the new HA version.
It shows like this: 
![image](https://github.com/bajansen/home-assistant-frank_energie/assets/65487781/3423ebf4-13b9-4e0b-ba03-bfbc63dd49be)

**Comment by Jasperwolsing** [comment] 2024-04-05 07:32
Im still on 2024.3 and have the same issue since yesterday

**Comment by HiDiHo01** [comment] 2024-04-05 07:35
It's a API Error

Op vr 5 apr 2024 09:33 schreef Jasperwolsing ***@***.***>:

**Comment by DCSBL** [comment] 2024-04-05 07:39
Duplicate of https://github.com/bajansen/home-assistant-frank_energie/issues/99

**Closed by DCSBL** 2024-04-05 07:39 UTC
